services:
  db:
    container_name: db
    image: postgres:17-alpine

    volumes:
      - ./postgres/data:/var/lib/postgresql/data

    env_file:
      - ./envs/dev/fastapi/.env

    expose:
      - 5432

    restart: always

  backend:
    container_name: backend

    build:
      context: .
      dockerfile: ./dockerfiles/dev/fastapi/Dockerfile

    volumes:
      - ./core:/usr/src/app

    working_dir: /usr/src/app

    command: uvicorn main:app --reload --host 0.0.0.0

    ports:
      - 8000:8000

    env_file:
      - ./envs/dev/fastapi/.env

    restart: always

    depends_on:
      - db
